### ISSUE TITLE
panic error in dasgoclient  for run,lumi query

### ISSUE THREAD

**Issue by belforte** [dmwm/das2go#40]
I downloaded latest version from GH, and here's what I get, which is the same as with current version in CVMFS (v02.04.42 )
if I query for `run` or `lumi` separetly it is OK. but `--query 'lumi,run` or `--query 'run,lumi` fail. I have never seen this before. Could it be because of the odd dataset name, or just something I did wrong in that dataset ? Or is this a problem on dasgoclient ? If it is due to something I did in this test, no problem.

```
belforte@lxplus715/TestConfig> ./dasgoclient_amd64 --version
Build: git=v02.04.45 go=go1.17.7 date=2022-03-22 19:13:12.504084088 +0100 CET m=+0.001383466
belforte@lxplus715/TestConfig> ./dasgoclient_amd64 --query 'lumi,run dataset=/ThisIsATest/belforte-CrabAutoTest_userInputFiles-94ba0e06145abd65ccb1d21786dc7e1d/USER instance=prod/phys03'
panic: interface conversion: interface {} is json.Number, not []interface {}

goroutine 1 [running]:
github.com/dmwm/das2go/services.OrderByRunLumis({0xc000101c00, 0x46, 0x7c5b3f})
	/home/runner/go/pkg/mod/github.com/dmwm/das2go@v0.0.0-20220310203810-12589cef23f2/services/helpers.go:316 +0x8ea
github.com/dmwm/das2go/services.fileRunLumi({{0xc000408090, 0x83}, {0x7ffffae0dfca, 0x7d}, {0xc000345f40, 0x20}, 0xc000402870, {0xc000369720, 0x2, 0x2}, ...}, ...)
	/home/runner/go/pkg/mod/github.com/dmwm/das2go@v0.0.0-20220310203810-12589cef23f2/services/helpers.go:303 +0x349
github.com/dmwm/das2go/services.LocalAPIs.RunLumi4Dataset(...)
	/home/runner/go/pkg/mod/github.com/dmwm/das2go@v0.0.0-20220310203810-12589cef23f2/services/dbs.go:167
reflect.Value.call({0x7c0140, 0xac37e8, 0xa93d40}, {0x7c59d7, 0x4}, {0xc0001d7108, 0x1, 0x40c34b})
	/opt/hostedtoolcache/go/1.17.7/x64/src/reflect/value.go:556 +0x845
reflect.Value.Call({0x7c0140, 0xac37e8, 0xc000161998}, {0xc0001d7108, 0x1, 0x1})
	/opt/hostedtoolcache/go/1.17.7/x64/src/reflect/value.go:339 +0xc5
main.processLocalApis({{0xc000408090, 0x83}, {0x7ffffae0dfca, 0x7d}, {0xc000345f40, 0x20}, 0xc000402870, {0xc000369720, 0x2, 0x2}, ...}, ...)
	/home/runner/work/dasgoclient/dasgoclient/main.go:1001 +0x505
main.process({0x7ffffae0dfca, 0x7d}, 0x0, {0x842680, 0x1}, 0x0, {0x0, 0x0}, {0x7cd077, 0x16}, ...)
	/home/runner/work/dasgoclient/dasgoclient/main.go:509 +0x130f
main.main()
	/home/runner/work/dasgoclient/dasgoclient/main.go:155 +0x120d
belforte@lxplus715/TestConfig> 
```

**Comment by belforte** [comment]
works, thanks !

**Comment by vkuznet** [comment]
@belforte for the reference, here is a link to CMSSW PR https://github.com/cms-sw/cmsdist/pull/7711 which should bring new version to cvmfs.
